- name: variable preference
  hosts: localhost
  # vars_files:
  #   - vars.yaml
  # vars_prompt:
  #   - name: WISHES
  #     prompt: "Please enter wishes"
  #     private: false
  # vars:
  #   WISHES: "Morning from PLAY variable"
  tasks:
  - name: check preference
    # vars:
    #   WISHES: "Morning from Task variable"
    ansible.builtin.debug:
      msg: "Hello, Good {{WISHES}}"

#1. args
#2.tasks
#3. variable file
#4. prompt
#5. play